language: node_js
node_js:
  - node
cache:
  directories:
  - node_modules

env:
  CI: false

before_install:
  
script:
  - npm test
  - npm run build

# branches:
#   only:
#     - feature_*

# after_success:
#   - ./travis_merge_script.sh
  